<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
NumPy Tutorial</p><br>

**NumPy** is a core-library for scientific computing in Python which provides high performance multidimentional array objects as well as concern tools or attributes for working on these array objects. 

Numerical Python or NumPy for short is one of the most foundational packages for numerical computing in Python. In fact, most advanced computational packages providing scientific functionality use it's array objects.

In these notebook tutorial following content will be covered.

- NumPy Array Objects
- Array Indexing 
- Math Operation
- Broadcastng

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>NumPy Array Objects</p><br>
NumPy array is a powerful array object with N-dimentional array object which is in the form of rows and columns, all of the same type, and is indexed by a tuple of nonnegative integers..

In [1]:
import numpy as np # installatijon command: pip install numpy

# a simple list
a_list = [1,2,3,4] 
print(a_list)
print(type(a_list))
'''output
[1, 2, 3, 4]
<class 'list'>
'''

print('--------------------------------------------')

# convert list to ndarray using numpy array function
list_to_ndarray = np.array(a_list)
print(list_to_ndarray)
print(type(list_to_ndarray))
'''output
[1 2 3 4]
<class 'numpy.ndarray'>
'''

[1, 2, 3, 4]
<class 'list'>
--------------------------------------------
[1 2 3 4]
<class 'numpy.ndarray'>


"output\n[1 2 3 4]\n<class 'numpy.ndarray'>\n"

In [2]:
'''
shape : gives row by columns
ndim  : rank of the array

The number of dimensions is the rank of the array; the shape of an array is a 
tuple of integers giving the size of the array along each dimension.
'''

array1D = np.array( [1,2,3,4] )
print('1D array \n', array1D) # 1D array | vector
print('Shape     : ', array1D.shape) # (4,)
print('Rank      : ', array1D.ndim)  # 1
print('Size      : ', array1D.size)  # 4
print('DatA Type : ', array1D.dtype) # int
'''output
1D array 
 [1 2 3 4]
Shape     :  (4,)
Rank      :  1
Size      :  4
DatA Type :  int64
'''

print('--------------------------------------------')

array2D = np.array( [ [1.,2.,3.,4.], [4.,3.,2.,1.] ] )
print('2D array \n',array2D) # 2D array | matrix
print('Shape     : ', array2D.shape) # (2,4)
print('Rank      : ', array2D.ndim)  # 2
print('Size      : ', array2D.size)  # 8
print('DatA Type : ', array2D.dtype) # float
'''output
2D array 
 [[1. 2. 3. 4.]
 [4. 3. 2. 1.]]
Shape     :  (2, 4)
Rank      :  2
Size      :  8
DatA Type :  float64
'''

print('--------------------------------------------')

array3D = np.array( [ [[1,2,3,4]], [[-1,-2,-3,-4]], [[1,2,3,4]] ] )
print('3D array \n', array3D)
print('Shape     : ', array3D.shape) # (3, 1, 4)
print('Rank      : ', array3D.ndim)  # 3
print('Size      : ', array3D.size)  # 12
print('DatA Type : ', array3D.dtype) # int
'''output
3D array 
 [[[ 1  2  3  4]]

 [[-1 -2 -3 -4]]

 [[ 1  2  3  4]]]
Shape     :  (3, 1, 4)
Rank      :  3
Size      :  12
DatA Type :  int64
'''

1D array 
 [1 2 3 4]
Shape     :  (4,)
Rank      :  1
Size      :  4
DatA Type :  int64
--------------------------------------------
2D array 
 [[1. 2. 3. 4.]
 [4. 3. 2. 1.]]
Shape     :  (2, 4)
Rank      :  2
Size      :  8
DatA Type :  float64
--------------------------------------------
3D array 
 [[[ 1  2  3  4]]

 [[-1 -2 -3 -4]]

 [[ 1  2  3  4]]]
Shape     :  (3, 1, 4)
Rank      :  3
Size      :  12
DatA Type :  int64


'output\n3D array \n [[[ 1  2  3  4]]\n\n [[-1 -2 -3 -4]]\n\n [[ 1  2  3  4]]]\nShape     :  (3, 1, 4)\nRank      :  3\nSize      :  12\nDatA Type :  int64\n'

In [3]:
'''
arange  : Return evenly spaced values within a given interval.     (doc words)
reshape : Gives a new shape to an array without changing its data. (doc words)
'''

numbers = np.arange(10) # It will create a 1D numpy array
print(numbers)          # 0,1,2,3,4,5,6,7,8,9
print(numbers.dtype)    # int
print(type(numbers))    # numpy.ndarray
'''output
[0 1 2 3 4 5 6 7 8 9]
int64
<class 'numpy.ndarray'>
'''

print('--------------------------------------------')

reshape_number = numbers.reshape(2,5) # It'll create a 2D numpy array. 
print(reshape_number)        # [[0 1 2 3 4] [5 6 7 8 9]]
print(reshape_number.dtype)  # int
print(type(reshape_number))  # numpy.ndarray
'''output
[[0 1 2 3 4]
 [5 6 7 8 9]]
int64
<class 'numpy.ndarray'>
'''

print('--------------------------------------------')

array2D = np.arange(20).reshape(4,5) # Create 2D array with shape (4,5) from 0 to 19 
print('2D array \n',array2D)         # 2D array | matrix
print('Shape     : ', array2D.shape) # (4,5)
print('Rank      : ', array2D.ndim)  # 2
print('Size      : ', array2D.size)  # 20
print('DatA Type : ', array2D.dtype) # int
'''output
2D array 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Shape     :  (4, 5)
Rank      :  2
Size      :  20
DatA Type :  int64
'''

print('--------------------------------------------')

array3D = np.arange(20).reshape(2, 2, 5) # Create 3D array with shape (2,2,5) from 0 to 19 
print('3D array \n',array3D)         # 2D array | matrix
print('Shape     : ', array3D.shape) # (2, 2, 5) | (channel , width, height) ; we've two 2 by 5 matrix
print('Rank      : ', array3D.ndim)  # 3
print('Size      : ', array3D.size)  # 20
print('DatA Type : ', array3D.dtype) # int
'''output
3D array 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
Shape     :  (2, 2, 5)
Rank      :  3
Size      :  20
DatA Type :  int64
'''

[0 1 2 3 4 5 6 7 8 9]
int64
<class 'numpy.ndarray'>
--------------------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
int64
<class 'numpy.ndarray'>
--------------------------------------------
2D array 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Shape     :  (4, 5)
Rank      :  2
Size      :  20
DatA Type :  int64
--------------------------------------------
3D array 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
Shape     :  (2, 2, 5)
Rank      :  3
Size      :  20
DatA Type :  int64


'output\n3D array \n [[[ 0  1  2  3  4]\n  [ 5  6  7  8  9]]\n\n [[10 11 12 13 14]\n  [15 16 17 18 19]]]\nShape     :  (2, 2, 5)\nRank      :  3\nSize      :  20\nDatA Type :  int64\n'

**NumPy** has a number of built in methods which help us quickly and easily create multidimensional arrays. We create a number of different size arrays with different shapes and different pre-filled values. 

In [4]:
all_zeros = np.zeros((2,2))   # Create an array of all zeros
print('All Zeros \n' ,all_zeros)     # Prints "[[ 0.  0.]
                                     #          [ 0.  0.]]"

print('--------------------------------------------')    
    
all_ones = np.ones((1,2))       # Create an array of all ones
print('All Ones \n', all_ones)  # Prints "[[ 1.  1.]]"

print('--------------------------------------------')

filled_array = np.full((2,2), 3)                          # Create a constant array
print('Filled with specified valued \n', filled_array)    # Prints "[[ 3.  3.]
                                                          #          [ 3.  3.]]"
print('--------------------------------------------')
    
identity_mat = np.eye(2)                   # Create a 2x2 identity matrix
print('Identity Matrix \n', identity_mat)  # Prints "[[ 1.  0.]
                                           #          [ 0.  1.]]"

print('--------------------------------------------')    
    
random_normal_distro = np.random.random((2,2))  # Create an array filled with random values
print('Normal Distribution \n', random_normal_distro)   

print('--------------------------------------------')    

evenly_spaced_ranged_number = np.linspace(1,3,10) # range 1 to 3, generate 10 digit with evely spaced
print('Evely spaced number in givend range \n', evenly_spaced_ranged_number)

print('--------------------------------------------') 

linspace_reshape = np.linspace(1,3,10).reshape(2,5)
print('2D array \n',linspace_reshape)         # 2D array | matrix
print('Shape               : ', linspace_reshape.shape) # (2, 5) 
print('Rank                : ', linspace_reshape.ndim)  # 2
print('Size                : ', linspace_reshape.size)  # 10
print('DatA Type           : ', linspace_reshape.dtype) # float
print('Converted Data Type : ', linspace_reshape.astype('int64').dtype) # convert float to int 
print('2D array \n',linspace_reshape.astype('int64')) # But this will truncated numbers after decimal

All Zeros 
 [[0. 0.]
 [0. 0.]]
--------------------------------------------
All Ones 
 [[1. 1.]]
--------------------------------------------
Filled with specified valued 
 [[3 3]
 [3 3]]
--------------------------------------------
Identity Matrix 
 [[1. 0.]
 [0. 1.]]
--------------------------------------------
Normal Distribution 
 [[0.64609114 0.86967861]
 [0.44188741 0.77588286]]
--------------------------------------------
Evely spaced number in givend range 
 [1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]
--------------------------------------------
2D array 
 [[1.         1.22222222 1.44444444 1.66666667 1.88888889]
 [2.11111111 2.33333333 2.55555556 2.77777778 3.        ]]
Shape               :  (2, 5)
Rank                :  2
Size                :  10
DatA Type           :  float64
Converted Data Type :  int64
2D array 
 [[1 1 1 1 1]
 [2 2 2 2 3]]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>Array Indexing</p><br>

**Numpy** offers several ways to index into arrays. We may want to select a subset of our data or individual elements. Most common ways are:

- Slicing
- Integer Array Indexing / Fnacy Indexing
- Boolean Indexing

- **Slicing**
Like in Python lists, NumPy arrays can be sliced.

In [5]:
array2D = np.arange(0,40,2).reshape(4,5)
print(array2D) # shape : (4,5)
'''output
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]
'''

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


'output\n[[ 0  2  4  6  8]\n [10 12 14 16 18]\n [20 22 24 26 28]\n [30 32 34 36 38]]\n'

In [6]:
'''
Use slicing to pull out the subarray from the orignial array.
Le's say we want to get following sub-array from array2D.
This located at row (1,2) and column (1,2).

[12 14]
[22 24]

So, we need to do somthing like array2D[row-range, column-range]. Note that, 
while indexing we need to range 1 step more, as we do 
in np.arange(0,10) <- go 0 to 9 but not 10.

'''
# and columns 1 and 2; b is the following array of shape (2, 2):

sliced_array_1 = array2D[1:3, 1:3] # look we set 1:3 <- go 1 to 2 but not include 3
print(sliced_array_1)
'''output
[[12 14]
 [22 24]]
'''

print('--------------------------------------------') 

sliced_array_2 = array2D[:, 1:4] # The 'bare' slice [:] will asign to all values in an array
print(sliced_array_2)
'''output
[[ 2  4  6]
 [12 14 16]
 [22 24 26]
 [32 34 36]]
'''

print('--------------------------------------------') 

sliced_array_3 = array2D[:4, 2:] # row: 0 to 3 ; column: 2 to all
print(sliced_array_3)

'''output
[[ 4  6  8]
 [14 16 18]
 [24 26 28]
 [34 36 38]]
'''



'''
More practice. array2D:

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]

Let's get some specific portion.

1. [16 18],
   [26 28]

2. [20 22 24],
   [30 32 34] 
   
3. [14 16],
   [24 26],
   [34 36]
'''

print('--------------------------------------------') 

sliced_array_4 = array2D[1:3, 3:] # row: 1 to 2 ; column: 3 to all
print('1 \n', sliced_array_4)
'''output
1 
 [[16 18]
 [26 28]]
'''

print('--------------------------------------------') 

sliced_array_5 = array2D[2:, 0:3] # row: 2 to all ; column: 0 to 2
print('2 \n', sliced_array_5)
'''output
2 
 [[20 22 24]
 [30 32 34]]
'''

print('--------------------------------------------') 

sliced_array_6 = array2D[1:, 2:4] # row: 1 to all ; column: 2 to 3
print('3 \n', sliced_array_6)
'''output
3 
 [[14 16]
 [24 26]
 [34 36]]
'''

[[12 14]
 [22 24]]
--------------------------------------------
[[ 2  4  6]
 [12 14 16]
 [22 24 26]
 [32 34 36]]
--------------------------------------------
[[ 4  6  8]
 [14 16 18]
 [24 26 28]
 [34 36 38]]
--------------------------------------------
1 
 [[16 18]
 [26 28]]
--------------------------------------------
2 
 [[20 22 24]
 [30 32 34]]
--------------------------------------------
3 
 [[14 16]
 [24 26]
 [34 36]]


'output\n3 \n [[14 16]\n [24 26]\n [34 36]]\n'

In [7]:
'''
A slice of an array is a view into the same data, so modifying it
will modify the original array.
'''

sliced_array_4 = array2D[1:3, 3:] # row: 1 to 2 ; column: 3 to all
print('Before \n', sliced_array_4)
'''output
Before 
 [[16 18]
 [26 28]]
'''

sliced_array_4[0, 0] = 77  
print('After \n', sliced_array_4)  
'''output
After 
 [[77 18]
 [26 28]]
'''

Before 
 [[16 18]
 [26 28]]
After 
 [[77 18]
 [26 28]]


'output\nAfter \n [[77 18]\n [26 28]]\n'

---

- **Fancy Indexing**<br>
Facny Indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [8]:
'''
To select out a subset of the rows in a particular order, we can simply pass a list or 
ndarray of integers specifying the desired order. Here is an example whose shape is 
(8,4). We would like to select out row 3,4,7 (randomly choosen)
'''
fancy_index = np.arange(32).reshape(8,4)
fancy_index
'''output
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])
'''

'output\narray([[ 0,  1,  2,  3],\n       [ 4,  5,  6,  7],\n       [ 8,  9, 10, 11],\n       [12, 13, 14, 15],\n       [16, 17, 18, 19],\n       [20, 21, 22, 23],\n       [24, 25, 26, 27],\n       [28, 29, 30, 31]])\n'

In [9]:
fancy_index[ [3,4,7] ] # a list of row number | fancy indexing 
'''output
array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [28, 29, 30, 31]])
'''

'output\narray([[12, 13, 14, 15],\n       [16, 17, 18, 19],\n       [28, 29, 30, 31]])\n'

In [10]:
fancy_index[ [1,2,6] ] # a list of row number | fancy indexing 
'''output
array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [24, 25, 26, 27]])
'''

'output\narray([[ 4,  5,  6,  7],\n       [ 8,  9, 10, 11],\n       [24, 25, 26, 27]])\n'

In [11]:
fancy_index[ [-3,-5,-1] ] # a list of row number | fancy negative indexing 
'''output
array([[20, 21, 22, 23],
       [12, 13, 14, 15],
       [28, 29, 30, 31]])
'''

'output\narray([[20, 21, 22, 23],\n       [12, 13, 14, 15],\n       [28, 29, 30, 31]])\n'

In [12]:
'''
let's observe if we pass two list what will happen. Generally it selects an one dimentional
array of elements corresponding to each tuple of indices. For example: if we do like:

fancy_index[[2,4,3], [3,0,2]]
 
Here (2,3), (4,0), (3,2) would be selected. In simple words, (2,3) here 2 represent the row
number and 3 represent the index value of that row.


fancy_index = [[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]]
       
tuple (2,3) : 11
tuple (4,0) : 16
tuple (3,2) : 14
  
'''
fancy_index[[2,4,3], [3,0,2]] # array([11, 16, 14])

array([11, 16, 14])

**Note**: Regardless of how many dimensions the array has, the result of fancy indexng is always one-dimensional.

---

- **Boolean Indexing**<br>

In [13]:
bool_index = np.arange(32).reshape(4,8)
print(bool_index)
'''output
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
'''

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


'output\n[[ 0  1  2  3  4  5  6  7]\n [ 8  9 10 11 12 13 14 15]\n [16 17 18 19 20 21 22 23]\n [24 25 26 27 28 29 30 31]]\n'

In [14]:
bool_index < 20 # boolean expression
'''output
array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False]])
'''

'output\narray([[ True,  True,  True,  True,  True,  True,  True,  True],\n       [ True,  True,  True,  True,  True,  True,  True,  True],\n       [ True,  True,  True,  True, False, False, False, False],\n       [False, False, False, False, False, False, False, False]])\n'

In [15]:
'''
The often we use such operaton when we do thresholding on the data. We can use these 
operation as an index and can get the result based on the expression. Let's see some
of the examples.
'''
bool_index[ bool_index < 20 ] # only get the values which is less than 20
'''output
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])
'''

'output\narray([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,\n       17, 18, 19])\n'

In [16]:
'''
let's see some various example of using this.
'''
print(bool_index[ bool_index % 2 == 0 ])      # [ 0  2  4 ... 28 30]
print(bool_index[ bool_index % 2 != 0 ])      # [ 1  3  5  ... 29 31]
print(bool_index[ bool_index % 2 == 0 ] + 1)  # [ 1  3  5  ... 29 31]
'''output
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]
'''



'''
Methods for Boolean array are 1 (True) and 0 (False). In these case some usefull methods are:

- sum() | counting the True values
- any() | test whether one or more values in an array is True
- all() | checks if every value is True

'''
print(bool_index[ bool_index < 10 ].sum()) # 45
print(bool_index[ bool_index < 10 ].all()) # False
print(bool_index[ bool_index < 10 ].any()) # True

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]
45
False
True


**Indexing using `where(condition, [x, y])`**

In [17]:
arx = np.array([1,2,3,4,5])
ary = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

out = np.where(filter, arx, ary)
print(out) # [ 1 22  3 44  5]

[ 1 22  3 44  5]


In [18]:
mat = np.random.rand(5,5)
print(mat)
'''output
[[0.75961013 0.26437703 0.38670089 0.45042377 0.89735447]
 [0.90111231 0.19172774 0.27427801 0.72230241 0.46797088]
 [0.98030653 0.09138688 0.62995209 0.94627245 0.59041074]
 [0.05558522 0.33889589 0.44382129 0.61814205 0.8122214 ]
 [0.16439016 0.87836497 0.01341273 0.35888597 0.21486541]]
'''


np.where( mat > 0.5, 1000, -1) # if condition true, set 1000 else -1
'''output
array([[1000,   -1,   -1,   -1, 1000],
       [1000,   -1,   -1, 1000,   -1],
       [1000,   -1, 1000, 1000, 1000],
       [  -1,   -1,   -1, 1000, 1000],
       [  -1, 1000,   -1,   -1,   -1]])
'''

[[0.00130205 0.61188613 0.81656965 0.97445805 0.78154856]
 [0.51502097 0.8560138  0.69596501 0.65184602 0.22729479]
 [0.02518219 0.52348343 0.40938401 0.69805286 0.67975566]
 [0.80848624 0.39656759 0.17826131 0.06181285 0.12511895]
 [0.86846137 0.49787302 0.89109703 0.79060537 0.77698939]]


'output\narray([[1000,   -1,   -1,   -1, 1000],\n       [1000,   -1,   -1, 1000,   -1],\n       [1000,   -1, 1000, 1000, 1000],\n       [  -1,   -1,   -1, 1000, 1000],\n       [  -1, 1000,   -1,   -1,   -1]])\n'

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>Math and Statistical Operation</p><br>

Basic mathematical functions operate elementwise on arrays.

In [19]:
x = np.arange(0,4).reshape(2,2).astype('float64')
y = np.arange(5,9).reshape(2,2).astype('float64')

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))
'''output
[[ 5.  7.]
 [ 9. 11.]]
[[ 5.  7.]
 [ 9. 11.]]
'''

print('----------------------------')

# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))
'''output
[[-5. -5.]
 [-5. -5.]]
[[-5. -5.]
 [-5. -5.]]
'''


print('----------------------------')

# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))
'''output
[[ 0.  6.]
 [14. 24.]]
[[ 0.  6.]
 [14. 24.]]
'''

print('----------------------------')

# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))
'''output
[[0.         0.16666667]
 [0.28571429 0.375     ]]
[[0.         0.16666667]
 [0.28571429 0.375     ]]
'''

print('----------------------------')

# Elementwise square root; produces the array
print(np.sqrt(x))
'''output
[[0.         1.        ]
 [1.41421356 1.73205081]]
'''

[[ 5.  7.]
 [ 9. 11.]]
[[ 5.  7.]
 [ 9. 11.]]
----------------------------
[[-5. -5.]
 [-5. -5.]]
[[-5. -5.]
 [-5. -5.]]
----------------------------
[[ 0.  6.]
 [14. 24.]]
[[ 0.  6.]
 [14. 24.]]
----------------------------
[[0.         0.16666667]
 [0.28571429 0.375     ]]
[[0.         0.16666667]
 [0.28571429 0.375     ]]
----------------------------
[[0.         1.        ]
 [1.41421356 1.73205081]]


'output\n[[0.         1.        ]\n [1.41421356 1.73205081]]\n'

In [20]:
'''
We use the dot function to compute inner products of vectors, to multiply a vector 
by a matrix, and to multiply matrices. dot is available both as a function in the numpy
module and as an instance method of array objects. Note that, * is elementwise 
multiplication, not matrix multiplication. 
'''

x = np.arange(0,4).reshape(2,2).astype('float64')
y = np.arange(5,9).reshape(2,2).astype('float64')

v = np.array([5,1])
w = np.array([3, 4])

# Inner product of vectors; both produce 19
print(v.dot(w))     # 19
print(np.dot(v, w)) # 19

print('----------------------------')

# Matrix / vector product; both produce the rank 1 array [1 13]
print(x.dot(v))
print(np.dot(x, v))
# [ 1. 13.]
# [ 1. 13.]

print('----------------------------')

# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))
# [[ 7.  8.]
# [31. 36.]]

# [[ 7.  8.]
# [31. 36.]]

19
19
----------------------------
[ 1. 13.]
[ 1. 13.]
----------------------------
[[ 7.  8.]
 [31. 36.]]
[[ 7.  8.]
 [31. 36.]]


In [21]:
'''
Numpy provides many useful functions for performing computations on arrays;
one of the most useful is sum
'''

import numpy as np

x = np.arange(5,9).reshape(2,2).astype('int64')

print(x)
print(np.sum(x))          # Compute sum of all elements; prints "26"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[12 14]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[11 15]"

[[5 6]
 [7 8]]
26
[12 14]
[11 15]


In [22]:
'''
Sometimes we need to manipulate the data in array. It can be done by reshaping or transpose
the array. Transposing is a special form of reshaping that similarly returns a view on the 
underlying data without copying anything. 

When doing matrix computation, we may do this very often.
'''

arr = np.arange(10).reshape(2,5)
print('At first \n', arr)   # At first 
                            #  [[0 1 2 3 4]
                            #  [5 6 7 8 9]]
print()
print('After transpose \n', arr.T)
# After transpose 
#  [[0 5]
#  [1 6]
#  [2 7]
#  [3 8]
#  [4 9]]

print('----------------------------')
transpose = np.arange(10).reshape(2,5)
print(np.dot(transpose.T, transpose)) # (5x2).(2,5) | matrix multiplication
# [[25 30 35 40 45]
#  [30 37 44 51 58]
#  [35 44 53 62 71]
#  [40 51 62 73 84]
#  [45 58 71 84 97]]

At first 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

After transpose 
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
----------------------------
[[25 30 35 40 45]
 [30 37 44 51 58]
 [35 44 53 62 71]
 [40 51 62 73 84]
 [45 58 71 84 97]]


In [23]:
'''
statistical functions and concern used function, such as 

- mean
- min
- sum
- std
- median
- argmin, argmax
'''

ary = 10 * np.random.randn(2,5)
print('Mean   : ', np.mean(ary))     # 0.9414738037734729
print('STD    : ', np.std(ary))      # 5.897885490589387
print('Median : ', np.median(ary))   # 1.5337461352996276
print('Argmin : ', np.argmin(ary))   # 3
print('Argmax : ', np.argmax(ary))   # 2
print('Max    : ', np.max(ary))      # 10.399663734487659
print('Min    : ', np.min(ary))      # -9.849839643044087
print('Compute mean by column :', np.mean(ary, axis = 0)) # compute the means by column
# Compute mean by column : [-1.61785449  0.4643941   8.24396096 -6.32814416  3.94501261]
print('Compute median by row  : ', np.median(ary, axis = 1)) # compute the medians
# Compute median by row  :  [2.7236133  0.34387897]

Mean   :  -5.335632555625546
STD    :  8.09983543532644
Median :  -7.507170043685229
Argmin :  7
Argmax :  5
Max    :  8.975973966339764
Min    :  -19.81438021812959
Compute mean by column : [ -0.59505187  -4.36908074 -13.61092129   2.53436439 -10.63747326]
Compute median by row  :  [-7.40746237 -7.60687772]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>Universal Functions</p><br>

A universal functions or ufunc is a special function that performs element-wise operations on the data in ndarrays. Such as fast vectorized wrapper for simple functions that take one or more scalar values and produce one or more scalar results. Many ufuncs are simple element-wise transformation, like `sqrt` or ` exp`.

In [24]:
ary = np.arange(5)

print('Find root of each elements-wise \n', np.sqrt(ary))
print()
print('Find exponential for each element-wise \n', np.exp(ary))

# Find root of each elements-wise 
#  [0.         1.         1.41421356 1.73205081 2.        ]

# Find exponential for each element-wise 
#  [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


'''
np.maximum

This computed the element-wise maximum of the elements in two array and returned a single 
array as a result.
'''
print()
print('Max values between two array \n', np.maximum(np.sqrt(ary), np.exp(ary)))
print('----------------------------')
print()
# Max values between two array 
#  [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


'''
np.modf

Another unfunc but can return multiple arrays. It returns the fractional and integral parts 
of a floating point array.
'''
rem, num = np.modf(np.exp(ary))
print('Floating Number ', np.exp(ary))
print()
print('Remainder       ', rem)
print('Number          ', num)
print('----------------------------')
print()

# Floating Number  [ 1.         2.71828183  7.3890561  20.08553692 54.59815003]

# Remainder        [0.         0.71828183 0.3890561  0.08553692 0.59815003]
# Number           [ 1.  2.  7. 20. 54.]



'''
np.ceil

Return the ceiling of the input, element-wise.
'''
ceil_num = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(ceil_num)                # [-1.7 -1.5 -0.2  0.2  1.5  1.7  2. ]
print(np.ceil(ceil_num))       # [-1. -1. -0.  1.  2.  2.  2.]


''' not ufunc

np.around

Evenly round to the given number of decimals.
'''
print(np.around(ceil_num))    # [-2. -2. -0.  0.  2.  2.  2.]
print('----------------------------')
print()

'''
np.absolute | np.abs | np.fabs

Calculate the absolute value element-wise.
'''
absl = np.array([-1, 2])
print('Absolute of Real Values              ', np.abs(absl))
print('Absolute of Real Values with Float   ', np.fabs(absl))
print('Absolute of Complex Values          ', np.abs(1.2 + 1j))

# Absolute of Real Values               [1 2]
# Absolute of Real Values with Float    [1. 2.]
# Absolute of Complex Values           1.5620499351813308

Find root of each elements-wise 
 [0.         1.         1.41421356 1.73205081 2.        ]

Find exponential for each element-wise 
 [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]

Max values between two array 
 [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
----------------------------

Floating Number  [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]

Remainder        [0.         0.71828183 0.3890561  0.08553692 0.59815003]
Number           [ 1.  2.  7. 20. 54.]
----------------------------

[-1.7 -1.5 -0.2  0.2  1.5  1.7  2. ]
[-1. -1. -0.  1.  2.  2.  2.]
[-2. -2. -0.  0.  2.  2.  2.]
----------------------------

Absolute of Real Values               [1 2]
Absolute of Real Values with Float    [1. 2.]
Absolute of Complex Values           1.5620499351813308


---

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>NumPy Random</p><br>

- np.random.rand
- np.random.randn
- np.random.random
- np.random.random_sample
- np.random.randint

- np.random.normal
- np.ranodm.uniform
- np.random.seed
- np.random.shuffle
- np.random.choice

In [25]:
'''
np.random.rand()

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``
'''
ary = np.random.rand(5,2) # shape: 5 row, 2 column
print('np.random.rand() \n', ary)
print('----------------------------')
print()

'''
np.random.randn

Return a sample (or samples) from the "standard normal" distribution.
'''
ary = np.random.randn(6)
print('1D array: np.random.randn() \n', ary)
ary = np.random.randn(3,3)
print('2D array: np.random.randn() \n', ary)
print('----------------------------')
print()

'''
np.random.random. 
numpy.random.random() is actually an alias for numpy.random.random_sample()

Return a sample (or samples) from the "standard normal" distribution.
'''
ary = np.random.random((3,3))
print('np.random.randn() \n', ary)
ary = np.random.random_sample((3,3))
print('np.random.random_sample() \n', ary)
print('----------------------------')
print()

'''
np.random.randint. 
Return random integers from low (inclusive) to high (exclusive)

Return random integers from the “discrete uniform” distribution of the specified 
dtype in the “half-open” interval [low, high). If high is None (the default), 
then results are from [0, low).

'''
ary = np.random.randint(low = 2, high = 6, size = (5,5))
print('np.random.randint() \n', ary)
ary = np.random.randint(low = 2, high = 6)
print('np.random.randint() :', ary)

np.random.rand() 
 [[0.55094699 0.61238167]
 [0.26608784 0.29214291]
 [0.69588066 0.28535539]
 [0.45613936 0.41822787]
 [0.44847302 0.67555346]]
----------------------------

1D array: np.random.randn() 
 [ 1.13204947 -1.66378404  0.75936891 -0.47352799  0.64239676  0.42043522]
2D array: np.random.randn() 
 [[-0.28349728 -1.00318228  0.53157892]
 [ 1.03549163 -0.17072524 -1.4363159 ]
 [ 0.71092646 -0.8575305  -0.79499979]]
----------------------------

np.random.randn() 
 [[0.52406923 0.99575498 0.35206789]
 [0.37646092 0.84825033 0.11700386]
 [0.55466916 0.3683915  0.12921485]]
np.random.random_sample() 
 [[0.02301325 0.45993064 0.41587527]
 [0.65257846 0.94706172 0.40290819]
 [0.20296816 0.83054246 0.32817939]]
----------------------------

np.random.randint() 
 [[2 3 2 4 2]
 [2 4 4 4 5]
 [2 2 3 3 5]
 [5 2 2 5 2]
 [2 4 5 3 4]]
np.random.randint() : 4


---

**Note**: `np.random.rand()` vs `np.random.random_samples()`

Both functions generate samples from the uniform distribution on 0, 1). The only difference is in how the arguments are handled. With `numpy.random.rand`, the length of each dimension of the output array is a separate argument. With `numpy.random.random_sample`, the shape argument is a single tuple.

In [26]:
'''
np.random.normal()

Draw random samples from a normal (Gaussian) distribution. This is Distribution is 
also known as Bell Curve because of its characteristics shape.
'''
mu, sigma = 0, 0.1 # mean and standard deviation
print('np.random.normal() \n',np.random.normal(mu, sigma, 10)) # from doc
print('----------------------------')
print()

'''
np.random.uniform()

Draw samples from a uniform distribution
'''
print('np.random.uniform() \n', np.random.uniform(-1,0,10))
print('----------------------------')
print()

'''
np.random.seed()
'''
np.random.seed(3) # seed the result

'''
np.random.shuffle

Modify a sequence in-place by shuffling its contents
'''

ary = np.arange(9).reshape((3, 3))
print('Before Shuffling \n', ary)

np.random.shuffle(ary)
print('After Shuffling \n', ary)
print('----------------------------')
print()

'''
np.random.choice

Generates a random sample from a given 1-D array
'''
ary = np.random.choice(5, 3) # Generate a uniform random sample from np.arange(5) of size 3:
print('np.random.choice() \n', ary) # This is equivalent to np.random.randint(0,5,3)

np.random.normal() 
 [-0.04331232  0.08852014  0.02700918 -0.03466447  0.02897117  0.01905231
  0.01245069  0.1037221   0.12891169  0.06164933]
----------------------------

np.random.uniform() 
 [-0.02229202 -0.4628001  -0.69672588 -0.0584059  -0.39434806 -0.03984935
 -0.70193723 -0.09344746 -0.88634446 -0.02888323]
----------------------------

Before Shuffling 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
After Shuffling 
 [[3 4 5]
 [0 1 2]
 [6 7 8]]
----------------------------

np.random.choice() 
 [1 3 0]


Some used functions:

- sort()
- unique()
- vstack() and hstack()
- ravel()
- tile()
- concatenate()

In [27]:
'''
sort() 
'''
# create a 10 element array of randoms
unsorted = np.random.randn(10)
print('Unsorted \n', unsorted)

# inplace sorting
unsorted.sort() 
print('Sorted \n', unsorted)

print()
print('----------------------------------')


'''
unique()
'''
ary = np.array([1,2,1,4,2,1,4,2])
print('Unique values : ', np.unique(ary))
print()
print('----------------------------------')


'''
vstack and hstack
'''
arx = np.array([[1,2,3],[3,4,5]])
ary = np.array([[4,5,6],[7,8,9]])
print('Vertical Stack \n', np.vstack((arx,ary)))
print('Horizontal Stack \n', np.hstack((arx,ary)))
print('Concate along columns \n', np.concatenate([arx, ary], axis = 0)) # similar vstack
print('Concate along rows \n', np.concatenate([arx, ary], axis = 1))    # similar hstack 
print()
print('----------------------------------')


'''
ravel :  convert one numpy array into a single column 
'''
ary = np.array([[1,2,3],[3,4,5]])
print('Ravel \n', ary.ravel())
print()
print('----------------------------------')


'''
tile()
'''
ary = np.array([-1, 0, 1])
ary_tile = np.tile(ary, (4, 1)) # Stack 4 copies of v on top of each other
print('tile array \n', ary_tile)

Unsorted 
 [ 0.1841282  -1.00595517 -0.34198034 -0.04472413  0.27844092 -0.58089402
 -0.15151488 -1.14743417 -0.61100002 -1.18951737]
Sorted 
 [-1.18951737 -1.14743417 -1.00595517 -0.61100002 -0.58089402 -0.34198034
 -0.15151488 -0.04472413  0.1841282   0.27844092]

----------------------------------
Unique values :  [1 2 4]

----------------------------------
Vertical Stack 
 [[1 2 3]
 [3 4 5]
 [4 5 6]
 [7 8 9]]
Horizontal Stack 
 [[1 2 3 4 5 6]
 [3 4 5 7 8 9]]
Concate along columns 
 [[1 2 3]
 [3 4 5]
 [4 5 6]
 [7 8 9]]
Concate along rows 
 [[1 2 3 4 5 6]
 [3 4 5 7 8 9]]

----------------------------------
Ravel 
 [1 2 3 3 4 5]

----------------------------------
tile array 
 [[-1  0  1]
 [-1  0  1]
 [-1  0  1]
 [-1  0  1]]


In [28]:
# Set Function

s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

print( np.intersect1d(s1, s2) ) 
print( np.union1d(s1, s2) )
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2
print( np.in1d(s1, s2) ) # which element of s1 is also in s2

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']
['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


---

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>Broadcasting</p><br>

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array

In [29]:
start = np.zeros((4,3))
print(start)

'''output
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
'''

# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])

y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

'''output
[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]
'''

# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)
'''output
[[0]
 [1]
 [2]
 [3]]
'''

# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

'''output
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
'''

# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start + add_scalar)
'''output
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
'''

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]
[[0]
 [1]
 [2]
 [3]]
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


'output\n[[1. 1. 1.]\n [1. 1. 1.]\n [1. 1. 1.]\n [1. 1. 1.]]\n'

Broadcasting two arrays together follows these rules:

- If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
- The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
- The arrays can be broadcast together if they are compatible in all dimensions.
- After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
- In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

## Additional Resources

- [Official | Numpy](http://www.numpy.org/)
- [DataCamp | Numpy](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)